/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}', './lib/**/*.{js,ts,jsx,tsx}', './store/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131316',
        surface: '#131316',
        'on-surface': '#e5e1e6',
        'on-surface-variant': '#c8c5d0',
        'surface-variant': '#353438',
        'surface-bright': '#39393d',
        'surface-dim': '#131316',
        'surface-tint': '#c1c1fc',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1c1b1f',
        'surface-container': '#201f23',
        'surface-container-high': '#2a292d',
        'surface-container-highest': '#353438',
        'inverse-surface': '#e5e1e6',
        'inverse-on-surface': '#313034',
        primary: '#c1c1fc',
        'on-primary': '#2a2b5b',
        'primary-container': '#1a1b4b',
        'on-primary-container': '#8384ba',
        'primary-fixed': '#e1e0ff',
        'on-primary-fixed': '#141545',
        'primary-fixed-dim': '#c1c1fc',
        'on-primary-fixed-variant': '#404273',
        'inverse-primary': '#585a8d',
        secondary: '#adc6ff',
        'on-secondary': '#002e69',
        'secondary-container': '#4b8eff',
        'on-secondary-container': '#00285c',
        'secondary-fixed': '#d8e2ff',
        'on-secondary-fixed': '#001a41',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed-variant': '#004493',
        tertiary: '#c0c1ff',
        'on-tertiary': '#1000a9',
        'tertiary-container': '#09007c',
        'on-tertiary-container': '#7679ff',
        'tertiary-fixed': '#e1e0ff',
        'on-tertiary-fixed': '#07006c',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-tertiary-fixed-variant': '#2f2ebe',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#918f9a',
        'outline-variant': '#46464f',
        // Legacy / fallback to prevent total UI break
        success: '#1FD18B',
        danger: '#FF5C75',
        muted: '#8B9BB4',
        brandLegacy: '#4F8CFF',
      },
      spacing: {
        xs: '8px',
        'margin-mobile': '16px',
        xl: '80px',
        sm: '16px',
        gutter: '24px',
        lg: '48px',
        md: '24px',
        base: '4px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Hanken Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-mono': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};

