/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}', './lib/**/*.{js,ts,jsx,tsx}', './store/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0B0D11',
        'background-deep': '#0B0D11',
        surface: '#11131A',
        'surface-dim': '#11131A',
        'surface-bright': '#373941',
        'surface-container-lowest': '#0B0E15',
        'surface-container-low': '#191B22',
        'surface-container': '#1D1F27',
        'surface-container-high': '#272A31',
        'surface-container-highest': '#32353C',
        'on-surface': '#E1E2EC',
        'on-surface-variant': '#C2C6D6',
        'inverse-surface': '#E1E2EC',
        'inverse-on-surface': '#2E3038',
        outline: '#8C909F',
        'outline-variant': '#424753',
        'surface-tint': '#10B981',
        primary: '#10B981', // Emerald Green primary
        'on-primary': '#FFFFFF',
        'primary-container': '#0D9488', // Teal container
        'on-primary-container': '#FFFFFF',
        'inverse-primary': '#059669',
        secondary: '#6366F1', // Indigo / Lavender secondary
        'on-secondary': '#FFFFFF',
        'secondary-container': '#4F46E5',
        'on-secondary-container': '#FFFFFF',
        tertiary: '#FFB77B',
        'on-tertiary': '#4D2700',
        'tertiary-container': '#D87802',
        'on-tertiary-container': '#432100',
        error: '#EF4444',
        'on-error': '#FFFFFF',
        'error-container': '#991B1B',
        'on-error-container': '#FFFFFF',
        // Standardizing primary semantic keys
        emerald: '#10B981',
        teal: '#0D9488',
        indigo: '#6366F1',
        'brand-deep': '#11131A',
        success: '#10B981',
        danger: '#EF4444',
        muted: '#C2C6D6',
      },
      spacing: {
        unit: '4px',
        'margin-main': '20px',
        'container-margin': '20px',
        'gutter-bento': '12px',
        gutter: '16px',
        'stack-gap': '16px',
        'card-padding': '24px',
        'section-padding': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        sans: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        mono: ['Geist', 'monospace'],
        'mono-data': ['Geist', 'monospace'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-amount': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-balance': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'amount-md': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '0.75rem',
        md: '1rem',
        lg: '1.25rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '28px': '28px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
