/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}', './lib/**/*.{js,ts,jsx,tsx}', './store/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0B1020',
        'background-deep': '#0B1020',
        surface: '#141218',
        'surface-dim': '#141218',
        'surface-bright': '#3b383e',
        'surface-container-lowest': '#0f0d13',
        'surface-container-low': '#1d1b20',
        'surface-container': '#211f24',
        'surface-container-high': '#2b292f',
        'surface-container-highest': '#36343a',
        'on-surface': '#e6e0e9',
        'on-surface-variant': '#cbc4d2',
        'inverse-surface': '#e6e0e9',
        'inverse-on-surface': '#322f35',
        outline: '#948e9c',
        'outline-variant': '#494551',
        'surface-tint': '#cfbcff',
        primary: '#cfbcff',
        'on-primary': '#381e72',
        'primary-container': '#6750a4',
        'on-primary-container': '#e0d2ff',
        'inverse-primary': '#6750a4',
        secondary: '#cdc0e9',
        'on-secondary': '#342b4b',
        'secondary-container': '#4d4465',
        'on-secondary-container': '#bfb2da',
        tertiary: '#e7c365',
        'on-tertiary': '#3e2e00',
        'tertiary-container': '#c9a74d',
        'on-tertiary-container': '#503d00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        // Custom exact hex equivalents requested by user design rules
        emerald: '#10B981',
        cyan: '#06B6D4',
        indigo: '#6366F1',
        'brand-deep': '#111827',
        // Legacy mappings for smooth backward compatibility
        success: '#10B981', // Emerald
        danger: '#ffb4ab', // Error
        muted: '#cbc4d2', // On-surface variant
      },
      spacing: {
        unit: '4px',
        'container-margin': '20px',
        gutter: '16px',
        'card-padding': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Hanken Grotesk', 'sans-serif'],
        mono: ['Geist', 'monospace'],
        'mono-data': ['Geist', 'monospace'],
        'label-caps': ['Geist', 'monospace'],
      },
      fontSize: {
        'display-balance': ['48px', { lineHeight: '52px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        '28px': '28px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};


